INSERT INTO exercises(id, title, description, is_custom) VALUES
(1, 'Narrow push ups for triceps', '', false),
(2, 'Triceps dips', '', false),
(3, 'Reverse knuckle push ups for biceps', '', false),
(4, 'Reverse snow angel', '', false),
(5, 'Side bends', '', false),
(6, 'Elbow knee touch', '', false),
(7, 'Lay hip raise', '', false),
(8, 'Wide stance squats', '', false),
(9, 'Assisted pistol squats', '', false),
(10, 'Feet exercise', '', false),
(11, 'Knees rotation', '', false),
(12, 'Forward lunges', '', false),
(13, 'Side lunges', '', false),
(14, 'Elevated pike push ups', '', false),
(15, 'Neck rotation', '', false),
(16, 'Shoulder-width push ups', '', false),
(17, 'Legs down hold', '', false),
(18, 'Legs flutters', '', false),
(19, 'Crunches', '', false),
(20, 'Plank', '', false),
(21, 'Mountain climbers', '', false),
(22, 'Twist', '', false);

INSERT INTO exercises_body_parts(exercise_id, body_part_id) VALUES
(1, 4),
(1, 6),
(2, 4),
(2, 6),
(3, 4),
(3, 5),
(4, 7),
(5, 7),
(6, 7),
(7, 7),
(7, 9),
(8, 9),
(9, 9),
(10, 9),
(11, 9),
(12, 9),
(13, 9),
(14, 2),
(15, 1),
(16, 3),
(17, 8),
(18, 8),
(19, 8),
(20, 8),
(21, 8),
(22, 8);
